export default () => ({
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  PORT: parseInt(process.env.PORT ?? '4000', 10),
  API_PREFIX: process.env.API_PREFIX ?? 'api/v1',
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_URL: process.env.REDIS_URL ?? 'redis://localhost:6379',
  CORS_ORIGINS: process.env.CORS_ORIGINS ?? 'http://localhost:3000',
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  TRACKING_MODE: process.env.TRACKING_MODE ?? 'demo',
  GPS_INGEST_SECRET: process.env.GPS_INGEST_SECRET,
  CASHFREE_APP_ID: process.env.CASHFREE_APP_ID,
  CASHFREE_SECRET_KEY: process.env.CASHFREE_SECRET_KEY,
  CASHFREE_ENV: process.env.CASHFREE_ENV ?? 'sandbox',
  CASHFREE_WEBHOOK_SECRET: process.env.CASHFREE_WEBHOOK_SECRET,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM ?? 'bookings@shivasakti.in',
  APP_PUBLIC_URL: process.env.APP_PUBLIC_URL ?? 'http://localhost:3000',
  API_PUBLIC_URL: process.env.API_PUBLIC_URL ?? 'http://localhost:4000/api/v1',
  PARTNER_WEBHOOK_HMAC_SECRET: process.env.PARTNER_WEBHOOK_HMAC_SECRET ?? 'dev-partner-webhook-secret',
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_API_KEY_SID: process.env.TWILIO_API_KEY_SID,
  TWILIO_API_KEY_SECRET: process.env.TWILIO_API_KEY_SECRET,
  TWILIO_SMS_FROM: process.env.TWILIO_SMS_FROM,
  TWILIO_WHATSAPP_FROM: process.env.TWILIO_WHATSAPP_FROM,
  TWILIO_WHATSAPP_CONTENT_SID: process.env.TWILIO_WHATSAPP_CONTENT_SID,
  MAP_PROVIDER: process.env.MAP_PROVIDER ?? 'osm',
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
});
